'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class batch
    Public Property id As Integer
    Public Property batch1 As String
    Public Property year As String

    Public Overridable Property registrations As ICollection(Of registration) = New HashSet(Of registration)

End Class
