'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class course
    Public Property id As Integer
    Public Property course1 As String
    Public Property duration As Nullable(Of Integer)

    Public Overridable Property registrations As ICollection(Of registration) = New HashSet(Of registration)

End Class
