'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class Student_management_systemEntities2
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=Student_management_systemEntities2")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property batches() As DbSet(Of batch)
    Public Overridable Property courses() As DbSet(Of course)
    Public Overridable Property registrations() As DbSet(Of registration)
    Public Overridable Property users() As DbSet(Of user)

End Class
