'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class registration
    Public Property id As Integer
    Public Property firstname As String
    Public Property lastname As String
    Public Property nic As String
    Public Property course_id As Nullable(Of Integer)
    Public Property batch_id As Nullable(Of Integer)
    Public Property telno As Nullable(Of Integer)

    Public Overridable Property batch As batch
    Public Overridable Property course As course

End Class
